# Generated by Django 3.0.2 on 2020-01-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinder', '0003_add_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='thumbnail_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
