# Generated by Django 3.0.2 on 2020-01-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinder', '0004_add_recipe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='emoji',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
